services:
  manticore:
    image: manticoresearch/manticore
    environment:
      - EXTRA=1
    restart: always
    ports:
      - 9306:9306
      - 9308:9308
    networks:
      - net
  api:
    container_name: api
    build: .
    depends_on:
      - manticore
    ports:
      - 5000:5000
    networks:
      - net

networks:
  net:
    driver: bridge
